name: Build and Publish to GHCR

on:
  schedule:
    - cron: '0 0 * * 0'  # Sunday
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout original repository
        uses: actions/checkout@v3
        with:
          repository: mspgeek-community/matterbridge
          ref: master

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/matterbridge:latest
